/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DeividAlexander
 */
public class InterfazC extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public InterfazC() {
        initComponents();
        TextPrompt n=new TextPrompt ("Nombre(s) *", nombres);
        TextPrompt ap=new TextPrompt ("Apellido(s) *", apellidos);
        TextPrompt dc=new TextPrompt ("N° Documento *", documento);
        TextPrompt nt=new TextPrompt ("N° Celular *", telefono);
        TextPrompt drr=new TextPrompt ("Dirección de Residencia *", direccion);
        TextPrompt cel=new TextPrompt ("Correo Electrónico *", correo);
        TextPrompt cel2=new TextPrompt ("Verificación Correo *", correo2);
        TextPrompt c=new TextPrompt ("Crea una contraseña *", contrasena);
        TextPrompt c1=new TextPrompt ("Verificaciòn Contraseña *", contrasena2);
        
        tipodoc.setBackground(Color.white);
        
        genero.add(hombre);
        genero.add(mujer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        documento = new javax.swing.JTextField();
        hombre = new javax.swing.JRadioButton();
        mujer = new javax.swing.JRadioButton();
        apellidos = new javax.swing.JTextField();
        tipodoc = new javax.swing.JComboBox<>();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        correo2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bRegistrarse = new javax.swing.JButton();
        aceptarTyC = new javax.swing.JRadioButton();
        confNombre = new javax.swing.JLabel();
        confApellido = new javax.swing.JLabel();
        confGenero = new javax.swing.JLabel();
        confDocumento = new javax.swing.JLabel();
        confTelefono = new javax.swing.JLabel();
        confDireccion = new javax.swing.JLabel();
        confCorreo = new javax.swing.JLabel();
        confClave = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        contrasena2 = new javax.swing.JPasswordField();
        confTerminos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 554));
        setMinimumSize(new java.awt.Dimension(480, 554));

        jPanel1.setBackground(new java.awt.Color(80, 5, 182));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Datos  básicos ");

        nombres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));
        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });
        nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresKeyTyped(evt);
            }
        });

        documento.setToolTipText("");
        documento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));
        documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                documentoKeyTyped(evt);
            }
        });

        hombre.setText("Hombre");
        hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hombreActionPerformed(evt);
            }
        });

        mujer.setText("Mujer");

        apellidos.setToolTipText("");
        apellidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));
        apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidosKeyTyped(evt);
            }
        });

        tipodoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".....", "C.C", "C.E", "P.P" }));
        tipodoc.setMinimumSize(new java.awt.Dimension(45, 16));
        tipodoc.setPreferredSize(new java.awt.Dimension(45, 18));
        tipodoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipodocActionPerformed(evt);
            }
        });

        direccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        telefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });

        correo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });

        correo2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Datos de acceso");

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ATRÁS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bRegistrarse.setBackground(new java.awt.Color(8, 161, 255));
        bRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        bRegistrarse.setText("REGISTRARSE");
        bRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarseActionPerformed(evt);
            }
        });

        aceptarTyC.setText("Acepto todos los términos y condiciones");
        aceptarTyC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarTyCActionPerformed(evt);
            }
        });

        contrasena.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        contrasena2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(confTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                        .addComponent(confDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(62, 62, 62))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(confNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(confApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(confGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(hombre)
                                                .addGap(10, 10, 10)
                                                .addComponent(mujer)))
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(tipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(documento))
                                            .addComponent(confDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addComponent(jLabel7)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(correo2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(confClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(contrasena2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                                .addComponent(aceptarTyC)
                                .addComponent(confTerminos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(bRegistrarse)
                            .addGap(28, 28, 28)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hombre)
                            .addComponent(mujer)
                            .addComponent(tipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(confGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(confCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confClave, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptarTyC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confTerminos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrarse)
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Quieres formar parte de nosotros?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRATE AQUI");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel3)))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hombreActionPerformed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        Principal p = new Principal();
        p.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarseActionPerformed
        // REGISTRARSE
        int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0;
        String caracter="@";
        ///PROCESO DE VALIDACION
        
         //confirmacion de correo
         int rst=0;   
        char [] vector = correo.getText().toCharArray();
        for (int j = 0; j < correo.getText().length(); j++) {
            String letra = String.valueOf(vector[j]);
            
            if (caracter.equalsIgnoreCase(letra)) {
            rst++;    
        } }
        
       

        if (correo.getText().equals("")){
            confCorreo.setForeground(Color.red);
            confCorreo.setText("Espacios Obligatorios *");
            a=1;
        }
            
        else {  if (rst==0) {
            confCorreo.setForeground(Color.red);
            confCorreo.setText("Correo inválido");  
            a=1;
            }else{
  
            if(correo.getText().equals(correo2.getText())) {
                confCorreo.setForeground(Color.blue);
                confCorreo.setText("Los correos coinciden");
                a=0;}
            else{
                confCorreo.setForeground(Color.red);
                confCorreo.setText("Los correos NO coinciden");
                a=1;           
            }
        }
        }
         
        
           
        // confirmar contraseña

        if (contrasena.getText().equals("")){
            confClave.setForeground(Color.red);
            confClave.setText("Espacios Obligatorios *");
            b=1;
        }
        else {
            if(contrasena.getText().equals(contrasena2.getText())) {
                confClave.setForeground(Color.blue);
                confClave.setText("Las contraseñas coinciden");
                b=0;}
            else{
                confClave.setForeground(Color.red);
                confClave.setText("Las contraseñas NO coinciden");
                b=1;
            }
        }
        
        
        //confirmar nombre
        if (nombres.getText().equals(""))
        { confNombre.setForeground(Color.red);
            confNombre.setText("Espacio obligatorio *");
            c=1;
            }
        else{
            confNombre.setText("");
            c=0;}

        //confirmar apellido

        if (apellidos.getText().equals(""))
        { confApellido.setForeground(Color.red);
            confApellido.setText("Espacio obligatorio *");
            d=1;
            }
        else{
            confApellido.setText("");
            d=0;}
        
         //genero
        if (!mujer.isSelected()&&(!hombre.isSelected()))
        { confGenero.setForeground(Color.red);
            confGenero.setText("Espacio obligatorio*");
            e=1;
            }
        else{
            confGenero.setText("");
            e=0;}

        //confirmar documento
        if (documento.getText().equals("") || tipodoc.getSelectedIndex()==0)
        { confDocumento.setForeground(Color.red);
            confDocumento.setText("Espacio obligatorio*");
            f=1;
           }
        else{
             if (documento.getText().length()>10) {
             confDocumento.setForeground(Color.red);
            confDocumento.setText("Número muy extenso");
             f=1;  
            } else
            confDocumento.setText("");
            f=0;}

        //confirmar telefono
        if (telefono.getText().equals(""))
        { confTelefono.setForeground(Color.red);
            confTelefono.setText("Espacio obligatorio*");
            g=1;
           }
        else{
             if (telefono.getText().length()>10) {
             confTelefono.setForeground(Color.red);
            confTelefono.setText("Número muy extenso");
             g=1;  
            }else{
             if (telefono.getText().length()<10) {
             confTelefono.setForeground(Color.red);
            confTelefono.setText("Número muy corto");
             g=1;  
             
             }else{
            confTelefono.setText("");
            g=0;}
        
             }
        }
         //confirmar direccion

        if (direccion.getText().equals(""))
        { confDireccion.setForeground(Color.red);
            confDireccion.setText("Espacio obligatorio *");
            h=1;
            }
        else{
            confDireccion.setText("");
            h=0;}
        
        //condirmar terminos
        
        if (!this.aceptarTyC.isSelected())
        { confTerminos.setForeground(Color.red);
            confTerminos.setText("Por favor acepta nuestros Términos y Condiciones");
            i=1;}
        else{
            confTerminos.setText("");
            i=0;}
        
        
        
        
        //////////////////////////////////////
        //PROCESO DE ENVIAR DATOS
        if((a==0)&&(b==0)&&(c==0)&&(d==0)&&(e==0)&&(f==0)&&(g==0)&&(h==0)&&(i==0)){
        
        familiarSQL ff=new familiarSQL();
        Familiar dll;
        
        String nb = nombres.getText();
        String ap = apellidos.getText();
        String nd = this.documento.getText();
        String tp = String.valueOf(tipodoc.getSelectedItem());
        String gn="";
        if (hombre.isSelected()) {
          gn="Hombre";
        } else {
          gn="Mujer";
        }
        String code = this.documento.getText();
        String tel = this.telefono.getText();
        String dir = this.direccion.getText();
        String corr = correo.getText();
        String con = this.contrasena.getText();
        
        System.out.println(nd+" "+tp+" "+nb+" "+ap+" "+gn+" "+code+" "+tel+" "+dir+" "+corr+" "+con);
        
        dll = new Familiar (nd,tp,nb,ap,gn,code,tel,dir,corr,con);
        ff.registrar(dll);
        
    }
        
        
        
        
    }//GEN-LAST:event_bRegistrarseActionPerformed

    private void aceptarTyCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarTyCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarTyCActionPerformed

    private void tipodocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipodocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipodocActionPerformed

    private void documentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_documentoKeyTyped
        // TODO add your handling code here:
        char nit= evt.getKeyChar();
        if (Character.isDigit(nit)){}
        else {
            evt.consume();
            getToolkit().beep();}
    }//GEN-LAST:event_documentoKeyTyped

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        // TODO add your handling code here:
        char nit= evt.getKeyChar();
        if (Character.isDigit(nit)){}
        else {
            evt.consume();
            getToolkit().beep();}
    }//GEN-LAST:event_telefonoKeyTyped

    private void nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresKeyTyped
        // TODO add your handling code here:
        char nit= evt.getKeyChar();
        if ((Character.isLetter(nit)) || (Character.isSpaceChar(nit))){}
        else {
            evt.consume();
            getToolkit().beep();}
    }//GEN-LAST:event_nombresKeyTyped

    private void apellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosKeyTyped
        // TODO add your handling code here:
        char nit= evt.getKeyChar();
        if (Character.isLetter(nit) || Character.isSpaceChar(nit)){}
        else {
            evt.consume();
            getToolkit().beep();}
    }//GEN-LAST:event_apellidosKeyTyped

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazC().setVisible(true);
            }
        });
    
    
    
    
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aceptarTyC;
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton bRegistrarse;
    private javax.swing.JLabel confApellido;
    private javax.swing.JLabel confClave;
    private javax.swing.JLabel confCorreo;
    private javax.swing.JLabel confDireccion;
    private javax.swing.JLabel confDocumento;
    private javax.swing.JLabel confGenero;
    private javax.swing.JLabel confNombre;
    private javax.swing.JLabel confTelefono;
    private javax.swing.JLabel confTerminos;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JPasswordField contrasena2;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField correo2;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documento;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JRadioButton hombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton mujer;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox<String> tipodoc;
    // End of variables declaration//GEN-END:variables
}
