/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author MICHAEL
 */
public class InterfazU extends javax.swing.JFrame {

    private Object ps;

    /**
     * Creates new form Colsutar
     */
    public InterfazU() {
        initComponents();
        TextPrompt n=new TextPrompt ("Nombre(s)", nombre);
        TextPrompt ap=new TextPrompt ("Apellido(s)", apellidos);
        TextPrompt ge=new TextPrompt ("Género", this.genero);
        TextPrompt dc=new TextPrompt ("N° Documento", this.Ndoc);
        TextPrompt tp=new TextPrompt ("Tipo Documento", this.tipoD);
        TextPrompt nt=new TextPrompt ("N° Celular", this.celular);
        TextPrompt drr=new TextPrompt ("Dirección de Residencia", direccion);
        TextPrompt cel=new TextPrompt ("Correo Electrónico", this.Correo);
        TextPrompt cel2=new TextPrompt ("Verificación Correo", Correo1);
        TextPrompt c=new TextPrompt ("Crea una contraseña", this.contra);
        TextPrompt c1=new TextPrompt ("Verificaciòn Contraseña", contra1);
        
        
        
        this.Actualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombres = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        apellidos = new javax.swing.JTextField();
        tipoD = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        Ndoc = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        contra = new javax.swing.JPasswordField();
        Correo1 = new javax.swing.JTextField();
        contra1 = new javax.swing.JPasswordField();
        confTelefono = new javax.swing.JLabel();
        confDireccion = new javax.swing.JLabel();
        confClave = new javax.swing.JLabel();
        confCorreo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numConsultar = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();
        casillaContra = new javax.swing.JPasswordField();

        nombres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));
        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(80, 5, 182));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        apellidos.setEditable(false);
        apellidos.setToolTipText("");
        apellidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        tipoD.setEditable(false);
        tipoD.setToolTipText("");
        tipoD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        celular.setEditable(false);
        celular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));
        celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celularKeyTyped(evt);
            }
        });

        direccion.setEditable(false);
        direccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        Ndoc.setEditable(false);
        Ndoc.setToolTipText("");
        Ndoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        genero.setEditable(false);
        genero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        nombre.setEditable(false);
        nombre.setToolTipText("");
        nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        Correo.setEditable(false);
        Correo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        contra.setEditable(false);
        contra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        Correo1.setEditable(false);
        Correo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        contra1.setEditable(false);
        contra1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182), new java.awt.Color(80, 5, 182)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoD, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ndoc, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Correo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(confTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(celular)
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(confDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contra1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(confClave, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confClave, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizar Datos");

        numConsultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnConsultar.setBackground(new java.awt.Color(8, 161, 255));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("CONFIRMAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("N° Documento");

        btnAtras.setBackground(new java.awt.Color(255, 0, 51));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("ATRÁS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña");

        Actualizar.setBackground(new java.awt.Color(8, 161, 255));
        Actualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        Actualizar.setText("ACTUALIZAR");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        casillaContra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        casillaContra.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(casillaContra)
                                .addComponent(numConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                            .addGap(58, 58, 58)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(324, 324, 324))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(numConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(casillaContra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Actualizar)
                            .addComponent(btnAtras))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnConsultar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Principal p = new Principal();
        p.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // BOTON
        String cond = this.numConsultar.getText();
        String cond2 = this.casillaContra.getText();
        
        familiarSQL ff=new familiarSQL();
        ff.Consulta(cond, cond2);
        
        List<Familiar> lcal=new ArrayList();
        lcal=ff.listar();
        
        
        int con=0; 
        
        for (Familiar familiar : lcal) { 
            if((familiar.getNmDocumento().equals(cond)) && (familiar.getContraseña().equals(cond2))){        
            con++; } 
        }
        
        if (con>0) {
            ff.Consulta(cond, cond2);///ejecutar metodo 
            this.numConsultar.setText("");
            this.casillaContra.setText("");
        
        ///mostrar los datos en las caja de texto    
        this.tipoD.setText(ff.getFamiliar().getTipoDocumento());
        this.Ndoc.setText(ff.getFamiliar().getNmDocumento());
        this.nombre.setText(ff.getFamiliar().getNombre());
        this.apellidos.setText(ff.getFamiliar().getApellido());
        this.genero.setText(ff.getFamiliar().getGenero());
        this.celular.setText(ff.getFamiliar().getTelefono());
        this.direccion.setText(ff.getFamiliar().getDirección());
        this.Correo.setText(ff.getFamiliar().getCorreo());
        this.contra.setText(ff.getFamiliar().getContraseña());
        
        //habilitar cajas de texto
        this.celular.setEditable(true);
        this.direccion.setEditable(true);
        this.Correo.setEditable(true);
        this.contra.setEditable(true);
        this.contra1.setEditable(true);
        this.Correo1.setEditable(true);
        this.Actualizar.setEnabled(true);
        
        } else {
            JOptionPane.showMessageDialog(null, "El usuario NO fue encontrado \nInténtelo nuevamente");
            this.numConsultar.setText("");
            this.numConsultar.requestFocus();
            this.casillaContra.setText("");
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        
    int a=0,b=0,g=0,h=0;
        String caracter="@";
        ///PROCESO DE VALIDACION
        
         //confirmacion de correo
         int rst=0;   
        char [] vector = this.Correo.getText().toCharArray();
        for (int j = 0; j < Correo.getText().length(); j++) {
            String letra = String.valueOf(vector[j]);
            
            if (caracter.equalsIgnoreCase(letra)) {
            rst++;    
        } }
        
       

        if (Correo.getText().equals("")){
            confCorreo.setForeground(Color.red);
            confCorreo.setText("Espacios Obligatorios *");
            a=1;
        }
            
        else {  if (rst==0) {
            confCorreo.setForeground(Color.red);
            confCorreo.setText("Correo inválido");  
            a=1;
            }else{
  
            if(Correo.getText().equals(Correo1.getText())) {
                confCorreo.setForeground(Color.blue);
                confCorreo.setText("Los correos coinciden");
                a=0;}
            else{
                confCorreo.setForeground(Color.red);
                confCorreo.setText("Los correos NO coinciden");
                a=1;           
            }
        }
        }
         
        
           
        // confirmar contraseña

        if (contra.getText().equals("")){
            confClave.setForeground(Color.red);
            confClave.setText("Espacios Obligatorios *");
            b=1;
        }
        else {
            if(contra.getText().equals(contra1.getText())) {
                confClave.setForeground(Color.blue);
                confClave.setText("Las contraseñas coinciden");
                b=0;}
            else{
                confClave.setForeground(Color.red);
                confClave.setText("Las contraseñas NO coinciden");
                b=1;
            }
        }
        
        
       
        //confirmar telefono
        if (celular.getText().equals(""))
        { confTelefono.setForeground(Color.red);
            confTelefono.setText("Espacio obligatorio*");
            g=1;
           }
        else{
             if (celular.getText().length()>10) {
             confTelefono.setForeground(Color.red);
            confTelefono.setText("Número muy extenso");
             g=1;  
            }else{
             if (celular.getText().length()<10) {
             confTelefono.setForeground(Color.red);
            confTelefono.setText("Número muy corto");
             g=1;  
             
             }else{
            confTelefono.setText("");
            g=0;}
        
             }
        }
         //confirmar direccion

        if (direccion.getText().equals(""))
        { confDireccion.setForeground(Color.red);
            confDireccion.setText("Espacio obligatorio *");
            h=1;
            }
        else{
            confDireccion.setText("");
            h=0;}
        
        
     ///proceso de actualizacion   
     if((a==0)&&(b==0)&&(g==0)&&(h==0)){    
        familiarSQL ff=new familiarSQL();
        
        String nc = this.celular.getText();
        String dr = this.direccion.getText();
        String ce = this.Correo.getText();
        String ct = this.contra.getText();
        String doc = this.Ndoc.getText();
        
     ff.modificar(nc, dr, ce, ct, doc);
        
    ////////colocar todo por defecto
    this.Actualizar.setEnabled(false);
    this.celular.setEditable(false);
    this.direccion.setEditable(false);
    this.Correo.setEditable(false);
    this.contra.setEditable(false);
    this.Correo1.setEditable(false);
    this.contra1.setEditable(false);
    
        this.tipoD.setText("");
        this.Ndoc.setText("");
        this.nombre.setText("");
        this.apellidos.setText("");
        this.genero.setText("");
        this.celular.setText("");
        this.direccion.setText("");
        this.Correo.setText("");
        this.contra.setText("");
        this.Correo1.setText("");
        this.contra1.setText("");
        this.confClave.setText("");
        this.confCorreo.setText("");
    this.numConsultar.requestFocus();
     }   
    }//GEN-LAST:event_ActualizarActionPerformed

    private void celularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularKeyTyped
        // TODO add your handling code here:
        char nit= evt.getKeyChar();
        if (Character.isDigit(nit)){}
        else {
            evt.consume();
            getToolkit().beep();}
    }//GEN-LAST:event_celularKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Correo1;
    private javax.swing.JTextField Ndoc;
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JPasswordField casillaContra;
    private javax.swing.JTextField celular;
    private javax.swing.JLabel confClave;
    private javax.swing.JLabel confCorreo;
    private javax.swing.JLabel confDireccion;
    private javax.swing.JLabel confTelefono;
    private javax.swing.JPasswordField contra;
    private javax.swing.JPasswordField contra1;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField numConsultar;
    private javax.swing.JTextField tipoD;
    // End of variables declaration//GEN-END:variables

    private Connection getConection() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private Object setString(int i, String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class rs {

        private static boolean next() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public rs() {
        }
    }
}
